repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.17.0
    hooks:
    -   id: eslint
        args: [--fix]
-   repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: python3 -m pytest
        language: python
        additional_dependencies: [pre-commit, pytest]
        always_run: true
        pass_filenames: false
-   repo: local
    hooks:
    -   id: git-secrets
        name: Git Secrets
        description: git-secrets scans commits, commit messages, and --no-ff merges
        entry: git-secrets --pre_commit_hook
        language: script
